[package]
name = "hello"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.26"
rand = "0.9.0"
simplelog = "0.12.2"
windows = { version = "0.61.1", features = ["Win32_UI_Input_KeyboardAndMouse"] }
